### ISSUE TITLE
newlib?

### ISSUE THREAD

**Issue by sleirsgoevy** [OpenOrbis/OpenOrbis-PS4-Toolchain#101]
Somewhere in the repo I saw a reference to the newlib port, and a link to the repository, however it seems to be gone. Is it just "superseded" by musl, or is there something that makes a proper newlib port impossible?

**Comment by kiwidoggie** [comment]
Newlib is an absolute pain in the ass to build, even larger pain in the ass to integrate into LLVM. Musl has better overall support for libc and also building with musl doesn't require some old/incompatible versions of tooling just to build it.

**Comment by Cryptogenic** [comment]
Indeed newlib was superseded by musl, mostly because of how annoying the build issues are like kiwi mentioned.
