### ISSUE TITLE
MAP_POPULATE only exists on Linux yet it's defined in OO.

### ISSUE THREAD

**Issue by nkrapivin** [OpenOrbis/OpenOrbis-PS4-Toolchain#104]
The title.
Setting this flag will cause mmap to return `MAP_FAILED`.
Maybe do something like:
`#define MAP_POPULATE MAP_PREFAULT_READ`? (although that's not a good idea)

**Comment by CrazyVoidProgrammer** [comment]
this is because we had to use the  closest base we could find for headers and at the time that was freebsd headers, we had to work off of something, this can be addressed and removed in the future.  Thanks for bringing it to notice.

**Comment by Cryptogenic** [comment]
@CrazyVoidProgrammer is correct, however headers for things like mmap where it's so OS-specific, I'd like to address it.
