### ISSUE TITLE
PHDR segment not covered by LOAD segment on ld 2.34

### ISSUE THREAD

**Issue by kiwidoggie** [OpenOrbis/OpenOrbis-PS4-Toolchain#122]
LD 2.34 and newer lld version both enabled stricter checking of the linker script. This is now throwing errors on any new linkers.

https://stackoverflow.com/questions/63420037/error-phdr-segment-not-covered-by-load-segment

This leads me to believe that as well as with the prx issues complaining when compiled on ps4 for .prx's that segments are out of order, that ld now is complaining meaning that there is probably an issue with the linker script somewhere.

**Comment by zerofo** [comment]
```
ld: trainer_loader: error: PHDR segment not covered by LOAD segment
make[2]: *** [trainer_loader/CMakeFiles/trainer_loader.dir/build.make:98：trainer_loader/trainer_loader] 错误 1
make[1]: *** [CMakeFiles/Makefile2:232：trainer_loader/CMakeFiles/trainer_loader.dir/all] 错误 2
make: *** [Makefile:84：all] 错误 2
```
how can i fix it ?

**Comment by kiwidoggie** [comment]
Closing since it seems to be fixed somehow since then and now
