### ISSUE TITLE
Some STD functions not linked when compiling SPRX

### ISSUE THREAD

**Issue by OSM-Made** [OpenOrbis/OpenOrbis-PS4-Toolchain#123]
Some functions needed for std::string aren't defined for SPRX libraries. Some functions are working just by linking LibcInternal like std::vector and std::map.

**Comment by Cryptogenic** [comment]
If this is still an issue - could you provide some example classes/method pairings in the stdlib that fail to link?

**Comment by Cryptogenic** [comment]
Basically because we don't use musl for library samples, libcxx can't work properly. We can get musl working for libraries, but the crtlib will need to be reworked a bit to iterate `init_array` so that globals are initialized properly.
