### ISSUE TITLE
Release tarball does not have a common top directory

### ISSUE THREAD

**Issue by sleirsgoevy** [OpenOrbis/OpenOrbis-PS4-Toolchain#127]
The release tarball places all stuff in its root directory, and not in a single subdirectory. If unpacked with `tar -xvf` without first cd-ing into an empty directory, the archive will unpack on top of whatever files are already in the current directory, which is almost definitely not what the user expects. Consider archiving the directory itself, not the individual files.

**Comment by Cryptogenic** [comment]
CI now creates a common top-level directory when building the toolchain. Given these builds will be used when creating releases, this will no longer be an issue.
