### ISSUE TITLE
Missing libgcc

### ISSUE THREAD

**Issue by sleirsgoevy** [OpenOrbis/OpenOrbis-PS4-Toolchain#128]
The toolchain does not link to libgcc. This library contains helper functions that the compiled code is free to reference at any time.

An example demonstrating the issue:

```
volatile double _Complex a = 1;
volatile double _Complex b = 2;
volatile double _Complex c = a * b;
```

EDIT: the bundled musl binary also contains references to functions from this library, but due to the "lazy" static linkage this code does not appear in the binary unless explicitly called.

**Comment by nkrapivin** [comment]
Should be fixed in PR #156 .
