### ISSUE TITLE
create-eboot: address of DYNAMIC segment != address of .dynamic section

### ISSUE THREAD

**Issue by sleirsgoevy** [OpenOrbis/OpenOrbis-PS4-Toolchain#130]
This is not a problem on its own, but poses problems when debugging with gdb. gdb remote debugging protocol uses the offset of .dynamic as an offset for "defeating" ASLR, and the client uses the offset of the **section** to calculate the base address, which causes the mismatch.

Proposed solutions:

a. Write a proper .dynamic section that matches the DYNAMIC segment in the OELF.

b. If that is not possible, change the load address of the existing .dynamic section to the one of the DYNAMIC segment. The file offset will not change, thus any analysis tools will read the correct data, and dynamic linkers do not need that section anyway.

**Comment by Cryptogenic** [comment]
I believe I've addressed this with this commit https://github.com/OpenOrbis/create-fself/commit/c72bb09ad38c3cd8ab646854df8a4183b6282429#diff-3db5f0df1dd08fa1901b41a30ae06772a1dfe32af3cb8a29bf91dc2a6d562516

Needs testing to confirm.

**Comment by sleirsgoevy** [comment]
So you chose to forcibly place your crafted DYNAMIC segment on top of the real .dynamic section. What if the .dynamic section in the input is smaller than what you're emitting, and you end up overwriting unrelated data that follows it? Can that happen?

I think a better solution is to abandon the original .dynamic section and just make .dynamic section in the output have the address and size of your crafted segment.

**Comment by Cryptogenic** [comment]
Just to clarify, you think setting .dynamic's section and segment address + size should be set to that of `PT_SCE_DYNLIB_DATA`'s? Since the dynamic table is inside of dynlib data?

**Comment by sleirsgoevy** [comment]
I don't understand why you keep the original .dynamic section in the first place. IMO section headers should represent what is in the file, not what was in it.

**Comment by Cryptogenic** [comment]
Because the section table is copied from the original ELF. It's far easier to do that then it is to write a brand new section table from scratch. And the original dynamic section is actually in the final ELF iirc, it's just that a new dynamic is written for what the PS4's ELF loader expects. I keep the original section tables and linking for debugging reasons so that it's easier to throw into IDA or something and get loaded with a standard ELF loader.

**Comment by Cryptogenic** [comment]
Addressed in create-fself v1.2. https://github.com/OpenOrbis/create-fself/commit/0b1fe04878e55500fdeeb0d66de2eaf30a0b1ddf
