### ISSUE TITLE
ioctl header incorrect in libkernel

### ISSUE THREAD

**Issue by kiwidoggie** [OpenOrbis/OpenOrbis-PS4-Toolchain#132]
![image](https://user-images.githubusercontent.com/9152262/125670185-e2f48b37-23dc-4cec-81b2-f62c2ce5ffb4.png)

This should match the freebsd headers I believe? Otherwise can close the issue

**Comment by theorywrong** [comment]
See with Specter, it's because Sony have defined on both libc and libkernel. The best solution here is to check if he is not defined one time.
![image](https://user-images.githubusercontent.com/20625892/125847333-75dd5e4d-0197-46fa-8a9f-b762c42695cd.png)
