### ISSUE TITLE
This can't build in VS2019?

### ISSUE THREAD

**Issue by HH45137** [OpenOrbis/OpenOrbis-PS4-Toolchain#133]
VS2017 too big ,I can't use vs2019 build ?

Sorry, my english is so bad

**Comment by sleirsgoevy** [comment]
This project does not use Visual Studio's build system. The only purpose of the "solution" files is to instruct VS how to call OpenOrbis's build system. Thus the VS version should not matter, but that needs checking.

**Comment by HH45137** [comment]
> This project does not use Visual Studio's build system. The only purpose of the "solution" files is to instruct VS how to call OpenOrbis's build system. Thus the VS version should not matter, but that needs checking.

Thank you very much
