### ISSUE TITLE
setjmp/longjmp are missing from libc.a

### ISSUE THREAD

**Issue by sleirsgoevy** [OpenOrbis/OpenOrbis-PS4-Toolchain#134]
Title says all. There are `setjmp.lo` and `longjmp.lo` in `libc.a`, but they are empty.

**Comment by nkrapivin** [comment]
+1ing that.
Can't build Lua because of their absence.

**Comment by nkrapivin** [comment]
Wait a second, both seem to be implemented in OOMusl:
https://github.com/OpenOrbis/musl/blob/master/src/setjmp/x86_64/setjmp.s

Maybe use Musl's implementation of setjmp/longjmp? 🤔

**Comment by Cryptogenic** [comment]
If I'm reading correctly, this should be possible by simply copying that file into a ps4 arch directory, the lack of the ps4 arch directory for setjmp is probably why they're missing / not being compiled in. I'll try to give this a go and test in the next day or two.

**Comment by sleirsgoevy** [comment]
https://github.com/OpenOrbis/musl/pull/18
