### ISSUE TITLE
CE-34706-0 Install error

### ISSUE THREAD

**Issue by HH45137** [OpenOrbis/OpenOrbis-PS4-Toolchain#135]
I generated a PKG in the SAMPLE folder of Hello_World, but the INSTALLATION in PS4 showed a CE-34706-0 error

**Comment by nkrapivin** [comment]
Hello.
Can you tell which toolchain version you have, your OS, your compiler version, and your build steps (if possible).

**Comment by kiwidoggie** [comment]
This is a HEN-related issue I believe.
