### ISSUE TITLE
MiraLib Bindings

### ISSUE THREAD

**Issue by Cryptogenic** [OpenOrbis/OpenOrbis-PS4-Toolchain#16]
We'd like bindings provided for MiraLib to use in C, C++, Python, and Rust. The python binding is being tackled by myself, however help is welcome for the other bindings once the MiraLib Core (#15) goes up.

- [ ] C
- [ ] C++
- [ ] Python
- [ ] Rust

**Comment by kiwidoggie** [comment]
Closing this as this will be apart of `mira-vnext`'s repo
