### ISSUE TITLE
How compile the source code of OpenOrbis in windows? i want use Piglet.

### ISSUE THREAD

**Issue by darkxex** [OpenOrbis/OpenOrbis-PS4-Toolchain#169]
Hello, recently you made the pull request of piglet, and I want to use it, but extracting the openOrbis directory does not work because the "lib" folder is empty.

https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/pull/161

**Comment by nkrapivin** [comment]
Please use a nightly build from the "Actions" tab and install it manually (set the `OO_PS4_TOOLCHAIN` env var yourself)

**Comment by darkxex** [comment]
Thanks my friend

**Comment by darkxex** [comment]
Thanks my friend, I will try this.

**Comment by darkxex** [comment]
@nkrapivin are you using linux? because in windows, the samples  are not compiling.

**Comment by nkrapivin** [comment]
> @nkrapivin are you using linux? because in windows, the samples are not compiling.

Do you have LLVM 10.0.0 installed (and it's in PATH)?

**Comment by darkxex** [comment]
yes, I use llvm 10 ... if the sdk works for me with the 5.1 installer, the problem is that the nighty build does not work for me.

**Comment by kiwidoggie** [comment]
We are still in progress, you will need to use developer skillset to look at the issue and correct what is wrong. Most of the samples breaking is due to us moving stuff around/renaming/paths changing that we haven't had a chance yet to go through and clean up.

**Comment by darkxex** [comment]
Don't sorry, I will wait for 5.2

**Comment by kiwidoggie** [comment]
You can find experimental builds of the toolchain located here: https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/actions

Nothing is guaranteed to work, but it's up-to-date with what we are working on as we are working on things. Mileage may vary.
