### ISSUE TITLE
Temporarily remove mira-based samples

### ISSUE THREAD

**Issue by Cryptogenic** [OpenOrbis/OpenOrbis-PS4-Toolchain#171]
There's a few samples that are reliant on Mira, such as the `substitute_example` and `mira_jailbreak`. Where mira is currently in a weird state and substitute by extension is also, I don't think it really makes sense to have these samples for the v0.5.2 release.

However, I'd want them brought back at a later point when the new Mira is in a stable release state.

**Comment by Cryptogenic** [comment]
Will keep issue open until samples are re-added.

**Comment by kiwidoggie** [comment]
Closing this as the projects have been moved to mira-vnext repository (still WIP, not-released)
