### ISSUE TITLE
Keyboard sample needs rework

### ISSUE THREAD

**Issue by Cryptogenic** [OpenOrbis/OpenOrbis-PS4-Toolchain#172]
Keyboard sample as-is won't work, the `sceSysmoduleLoadModule()` call fails. This could be because you simply can't load it normally or because it conflicts with linking against `libSceKeyboard` directory. May need to be reworked to use `sceImeKeyboard*` functions from the IME library. That, or there's a bug somewhere that needs to be investigated and resolved. Either way, we should work on getting keyboard working and re-added, until then we'll take it out for v0.5.2.

**Comment by bucanero** [comment]
Seems it has been fixed in https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/pull/183
