### ISSUE TITLE
New Error W/ Compiling Samples

### ISSUE THREAD

**Issue by godreborn** [OpenOrbis/OpenOrbis-PS4-Toolchain#177]
I just upgraded openorbis, but I get an error.  I was able to compile the old version perfectly fine, so I don't know what the problem could be:

clang++ --target=x86_64-pc-freebsd12-elf -fPIC -funwind-tables -c  -isysroot /home/godreborn/openorbis -isystem /home/godreborn/openorbis/include -isystem /home/godreborn/openorbis/include/c++/v1 -o hello_world/x64/Debug/main.o hello_world/main.cpp
hello_world/main.cpp:1:10: fatal error: 'sstream' file not found
#include <sstream>
         ^~~~~~~~~
1 error generated.
make: *** [Makefile:83: hello_world/x64/Debug/main.o] Error 1

**Comment by Cryptogenic** [comment]
You must have a path set wrong because sample building is tested in the CI workflow.

**Comment by godreborn** [comment]
alright, I figured out the problem.  this can be closed.
