### ISSUE TITLE
script /extra/setup-toolchain.sh needs binary files /bin/linux to execute

### ISSUE THREAD

**Issue by DonatScript** [OpenOrbis/OpenOrbis-PS4-Toolchain#180]
Salam  @OpenOrbis-PS4-Toolchain community,

I'm facing `chmod` commands issue that said not all executable files exist, I don't see if there prerequisite to compile them before or assume to be there.

however I see the `build/build.sh` pointing to /`OpenOrbis-PS4-Toolchain/src/tools/create-eboot` that not exist as well

I'm using Ubuntu
```
$ bash ./setup-toolchain.sh
chmod: cannot access '/home/ps-dev/ps4toolchain/bin/linux/create-eboot': No such file or directory
chmod: cannot access '/home/ps-dev/ps4toolchain/bin/linux/create-lib': No such file or directory
chmod: cannot access '/home/ps-dev/ps4toolchain/bin/linux/readelf': No such file or directory

```

**Comment by theorywrong** [comment]
Hi !
You can download pre-compiled executable here.

just put the executable inside the folder and re-use the command 😄

**Comment by theorywrong** [comment]
https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/releases (link tool doesn’t work xP)
