### ISSUE TITLE
Compiling Samples on Windows

### ISSUE THREAD

**Issue by godreborn** [OpenOrbis/OpenOrbis-PS4-Toolchain#192]
not sure what's going on here, but I get this error.  llvm is installed with its path in environmental variables.  I have no issues on linux, so I thought I'd learn how to compile through windows, but this is causing a problem.  it's like it's not detecting llvm.  I'm using 13.0, tried older, and the beta of 13.1, and same error.  visual studio also gives this error:
![unknown](https://user-images.githubusercontent.com/13548481/148819549-67ed446a-cd28-4480-ad86-ff9fd95d5aea.png)

**Comment by Roko191** [comment]
Why not just use `build.bat` file on windows?

**Comment by godreborn** [comment]
I'm interested in doing this way.  besides, build.bat also errors.  AlAzif suggested I try it, but it doesn't work for me.

**Comment by Cryptogenic** [comment]
Currently building with makefiles is not supported, because the makefiles check `shell uname -s` to get the path for clang/ld. If build.bat also errors with similar issues, again your install is probably bad. Closing as not an issue in the toolchain.
