### ISSUE TITLE
getting console mac address

### ISSUE THREAD

**Issue by orginizations** [OpenOrbis/OpenOrbis-PS4-Toolchain#205]
Hi
Is there any way to get mac address of ps4 device or getting a unique id of a ps4 device?

**Comment by sleirsgoevy** [comment]
> Hi Is there any way to get mac address of ps4 device or getting a unique id of a ps4 device?

PS4 is FreeBSD, so the normal FreeBSD way of getting a MAC address should work once you escalate privileges. See [here](http://web.archive.org/web/20220421163605/https://freebsd-hackers.freebsd.narkive.com/8O2RE8kg/getting-mac-address) and [here](https://github.com/freebsd/freebsd-src/blob/release/9.0.0/lib/libc/net/getifaddrs.c).

**Comment by bucanero** [comment]
btw, there's an internal method `sceNetGetMacAddress()` but it needs to be reversed to confirm the parameters and return values
