### ISSUE TITLE
Undefined symbols

### ISSUE THREAD

**Issue by ac2pic** [OpenOrbis/OpenOrbis-PS4-Toolchain#239]
Could not find any definitions in this repo or musl. 
https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/blob/c63c9e68d53074603f626cf561edcbf42c1dfd45/include/orbis/_types/kernel.h#L12-L29

**Comment by ac2pic** [comment]
Missing an include here.
https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/blob/c63c9e68d53074603f626cf561edcbf42c1dfd45/include/orbis/_types/msg_dialog.h#L81

**Comment by illusion0001** [comment]
This come from freebsd helper https://man.freebsd.org/cgi/man.cgi?query=kqueue&apropos=0&sektion=0&manpath=FreeBSD+9.1-RELEASE&arch=default&format=html
