### ISSUE TITLE
Prerequisites for hello world sample

### ISSUE THREAD

**Issue by john-tornblom** [OpenOrbis/OpenOrbis-PS4-Toolchain#42]
I have tried to build and install the hello world sample on my ps4 using the linux v0.2 SDK, but when I start the example, I get an error message complaining about corruption. I get the same behavior when installing the hello world pkg file present in the linux v0.2 SDK release zip. I'm using the HEN payload distributed by ps4gentoo, do I need some other specific payload to actually launch homebrew produced by openorbis?

**Comment by eeply** [comment]
Yes, you need to use the mira-loader.bin as payload and send then the mira.elf to the loader. Otherwise the homebrew pkgs will fail, because mira patches the loading of the libc to the system one.

**Comment by john-tornblom** [comment]
Ah, right! I will give that a go, thanks!
