### ISSUE TITLE
Missing execution permission in the linux SDK

### ISSUE THREAD

**Issue by john-tornblom** [OpenOrbis/OpenOrbis-PS4-Toolchain#50]
The zip compression format does not preserve file permissions very well. Consider using tar.gz files instead, or use Info-Zip, which would simplify the installation on POSIX-based systems.

For more information on the issue, see https://stackoverflow.com/questions/10735297/maintain-file-and-folder-permissions-inside-archives

**Comment by Cryptogenic** [comment]
Noted, future releases will use .tar.gz - thanks :D
