### ISSUE TITLE
Potential Makefile improvements

### ISSUE THREAD

**Issue by john-tornblom** [OpenOrbis/OpenOrbis-PS4-Toolchain#54]
I have made some changes (which I believe are improvements) to the hello_world Makefile. For example:
- set the clang flag -isysroot to the SDK root,
- use the flag -isystem for system includes,
- use the x86_64-scei-ps4-elf target, and create orbis-ld wrapper script that appends SDK-specific linker arguments,
- generate gp4 file and param.sfo automatically.

I posted the Makefile as a gist at: https://gist.github.com/john-tornblom/b63467bd56ea8758c99a51d7b9ccdb78
the files create-gp4 and orbis-ld needs to be placed in $OO_PS4_TOOLCHAIN/bin/linux for the Makefile to work correctly.

**Comment by Cryptogenic** [comment]
Looks good with the exception of the `x86_64-scei-ps4-elf` target triple. I originally had the makefiles use that target but there's a big problem with it with C++, being that for whatever reason, that triple makes it so global object constructors were not put in `.init_array` but were rather put in `.ctors` (I think). This would lead to crashes whenever you tried to access a global C++ object (ie. a stringstream).

Switching from `x86_64-scei-ps4-elf` to `x86_64-pc-freebsd-elf` solved this issue and doesn't appear to have any drawbacks.

**Comment by john-tornblom** [comment]
Okey, it seems the clang ps4 target will append the flag -fno-use-init-array.
For future references: https://github.com/llvm/llvm-project/blob/2956cc50f3405ae32c8c6d6e2c63fe8cb6456fa2/clang/lib/Driver/ToolChains/PS4CPU.cpp#L237

**Comment by Cryptogenic** [comment]
> 
> 
> Okey, it seems the clang ps4 target will append the flag -fno-use-init-array.
> For future references: https://github.com/llvm/llvm-project/blob/2956cc50f3405ae32c8c6d6e2c63fe8cb6456fa2/clang/lib/Driver/ToolChains/PS4CPU.cpp#L237

Thanks for the insight, I was wondering what was causing the init arrays to be ignored. This has me wondering why they felt the need to make that change now, and if this is possibly connected to issue #53...

**Comment by Cryptogenic** [comment]
Originally I was going to include this in v0.5 however there's some overhauls I wanna do that will take a bit more time to do properly, and I'd like to push v0.5 for today in the interest of the Mira daemon. I'm going to postpone this until v0.6.
