### ISSUE TITLE
Unknown type name '__va_list' errors on samples

### ISSUE THREAD

**Issue by Cryptogenic** [OpenOrbis/OpenOrbis-PS4-Toolchain#6]
A few people have tested and with VS2019 (possibly other versions?), they've reported `unknown type name '__va_list'` errors in the `stdio.h.` header.

![](https://i.imgur.com/5mfSRLT.png)

**Comment by Cryptogenic** [comment]
Discovered the issue isn't in the toolchain itself, it's an issue in the newest LLVM / clang. On clang 7.0.1 this issue isn't present, but it is on 10.0.0.

**Comment by Tustin** [comment]
As a test, try including cstarg. Seems to generate an eboot for me
```cpp
#include <cstdarg>
#include <stdio.h>
#include <orbis/libkernel.h>
```

**Comment by Cryptogenic** [comment]
Root cause found, essentially Clang 10.0+ doesn't act like GCC anymore and therefore doesn't define `__GNUC__`, which is used by the libc headers for defining builtins. As per Clang 10.0 release notes:

> The -fgnuc-version= flag now controls the value of __GNUC__ and related macros. This flag does not enable or disable any GCC extensions implemented in Clang. Setting the version to zero causes Clang to leave __GNUC__ and other GNU-namespaced macros, such as __GXX_WEAK__, undefined.

source: https://releases.llvm.org/10.0.0/tools/clang/docs/ReleaseNotes.html

The best fix we came up with was to add a check in `sys/cdefs.h` for clang 10.0 and higher, and forcefully define `__GNUC__`.

```c
#if __clang_major__ >= 10 && !defined(__GNUC__)
#define __GNUC__ 3
#endif
```
