### ISSUE TITLE
Add libc/libSceFios2 dummy libraries for packages

### ISSUE THREAD

**Issue by Cryptogenic** [OpenOrbis/OpenOrbis-PS4-Toolchain#62]
We're going to attempt to transition Mira away from the Workaround8849 and ioctl hook for homebrew as it breaks a lot of games. Because the loader requires `sce_module/libc.prx` and `sce_module/libSceFios2.prx` and we cannot redistribute the real ones, we'll have dummy libraries that don't do anything since homebrew doesn't use these libraries anyway. Libc is static linked in, and fios2 contains exotic functions that (at least currently) aren't used. In the future, the fios2 stub can be updated to support functionality once reversed.

**Comment by sleirsgoevy** [comment]
I searched the source code for "workaround8849" and "ioctl" and can't seem to find anything. What is this about?

**Comment by Cryptogenic** [comment]
> 
> 
> I searched the source code for "workaround8849" and "ioctl" and can't seem to find anything. What is this about?

It's in the Mira codebase. Essentially the `sys_workaround8849` syscall and the `/dev/dipsw` `0x40048806` ioctl is hooked to trick the system into thinking it's a devkit. Devkits have the ability to load libc and fios2 from system where retail does not (I guess to enforce game developers to ship those modules for compatibility reasons).

While this works for homebrew (since we can't ship the libc and fios2 modules since we don't own them), it messes with games for some reason and causes many games to fail to load.

**Comment by sleirsgoevy** [comment]
Thanks for an explanation.

**Comment by Cryptogenic** [comment]
Addressed in commit d03b1c9ae64e8304cb947488efdf52d8bc8fa9cc.
