### ISSUE TITLE
`create-pkg` tool is missing

### ISSUE THREAD

**Issue by sleirsgoevy** [OpenOrbis/OpenOrbis-PS4-Toolchain#63]
`create-pkg` tool is described in the README.md but is missing from the repository, as well as the release tarball.

**Comment by Cryptogenic** [comment]
It exists but under a different name. It's not in the repository but the binary is in the release tarball as `PkgTool.Core` by maxton. The reason for the naming discrepancy is when this part of the readme was written we were going to roll our own create package tool, however maxton already had one so we used that instead. Will fix the readme though, thanks :D
