### ISSUE TITLE
Makefiles need to create intermediate directory

### ISSUE THREAD

**Issue by Cryptogenic** [OpenOrbis/OpenOrbis-PS4-Toolchain#7]
The makefiles for samples currently don't create the intermediate directory before building, so "no such file or directory" errors occur unless you make the dir in advance.

Meant to get to this before the toolchain dropped but it slipped through the cracks.

**Comment by VityaSchel** [comment]
I made x64/Debug in my project root but still getting /x64/Debug/*.o: No such file or directory
