### ISSUE TITLE
TLS support is broken

### ISSUE THREAD

**Issue by sleirsgoevy** [OpenOrbis/OpenOrbis-PS4-Toolchain#86]
Thread-local variable support is missing from the toolchain. Variables are accessed relative to `fs:0`, which seems to be initialized by the kernel linker. In particular, accessing thread-local variables doesn't yield the values set in static initializers.

EDIT: #84 is related

**Comment by Cryptogenic** [comment]
Confirmed working along with your PR in the MUSL repository.

```
Running toolchain unit test: Thread-Local Storage (TLS)
--
[*] Testing mbstowcs()
	[+] multibyte string = Hello world!
	[+] wide string      = Hello world!
	[*] Passed.
[*] Testing wbstombs()
	[+] multibyte string = Hello world!
	[+] wide string      = Hello world!
	[*] Passed.

--
2/2 tests pass. Test complete.
```
