### ISSUE TITLE
[NOT AN ISSUE] Confirmed working on a pure-HEN payload

### ISSUE THREAD

**Issue by sleirsgoevy** [OpenOrbis/OpenOrbis-PS4-Toolchain#89]
I can confirm that applications built using this toolchain can be run after applying a "HEN-only" (i.e. no Mira) payload. I think this does matter because players tend to use such payloads just because "Mira is for developers, you don't need it".

**Comment by Cryptogenic** [comment]
Yeah, this was one of the primary points to address in v0.4 with the fake libc/libSceFios2; removing the Mira dependency. Not only can you now run homebrew built with the toolchain without using Mira if you don't want to, but the hooks in Mira that were responsible for loading homebrew in the past were very problematic for running legitimate games.
