### ISSUE TITLE
Put libraries on CI

### ISSUE THREAD

**Issue by Cryptogenic** [OpenOrbis/OpenOrbis-PS4-Toolchain#9]
We should probably put libraries on Continuous Integration (CI) that way any updates can be pulled immediately from the artifacts without having to wait for them to be bundled in a release.

**Comment by valincius** [comment]
Hi, I can take care of any of these CI/CD things if you'd like to assign to me and include a little more detailed explanation of what you're after.

**Comment by valincius** [comment]
I started with this. Where do I get the "IDC Lib Documentation" that's required for OrbisLibGen?

**Comment by Cryptogenic** [comment]
> 
> 
> I started with this. Where do I get the "IDC Lib Documentation" that's required for OrbisLibGen?

I'm thinking of reworking a little bit how the libs are built because I think CrazyVoid left some stuff out actually, and the way it is done atm won't lend itself well to updated prototypes in the future.

**Comment by valincius** [comment]
Got it. I’ll hold off then. But I’m working on a docker image for this tool chain. should come in handy for future CI/CD jobs.
